apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: componenta-devfile-sample-go-basic-private-devfile-nested-kzbs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: componenta-devfile-sample-go-basic-private-devfile-nested-kzbs
    app.kubernetes.io/part-of: mc-golang-nested
  name: componenta-devfile-sample-go-basic-private-devfile-nested-kzbs
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: componenta-devfile-sample-go-basic-private-devfile-nested-kzbs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: componenta-devfile-sample-go-basic-private-devfile-nested-kzbs
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-gwiv-tenant/mc-golang-nested/componenta-devfile-sample-go-basic-private-devfile-nested-kzbs@sha256:a932db09e5cc7ce3098b553886c6e0b967eaa14308eab3de047e219a11c91a52
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 12m
            memory: 18Mi
status: {}
